### ISSUE TITLE
Cocoapods integration

### ISSUE THREAD

**Issue by shsteven** [matthewcheok/MCPanelViewController#1]
Great work!
Can you please make MCPanelViewController available in Cocoapods?

**Comment by matthewcheok** [comment]
I'm not sure how to write the cocoapods spec. Any inputs are welcomed!

**Comment by shsteven** [comment]
Something like this:

https://gist.github.com/shsteven/6931767

The file should exist as MCPanelViewController.podspec in the project directory.

Please change the metadata accordingly  : )

**Comment by matthewcheok** [comment]
Done

**Comment by shsteven** [comment]
thanks a bunch!
