### ISSUE TITLE
UIPanGestureRecognizer and manually presenting panel

### ISSUE THREAD

**Issue by yongeli** [matthewcheok/MCPanelViewController#12]
Hi, 

I'm trying to present the side panel onto screen with a pan gesture of left/right, as opposed to just the edge pan gestures.

Whenever I try to present the view manually with a pan gesture like so:

[self.tabBarController presentPanelViewController:tintedPanelViewController withDirection:MCPanelAnimationDirectionLeft];

the panel would flicker a few times (recreating itself over and over?) then present itself into view. 

Any ideas what would be causing this?

Thank you for the project and thanks for any help on this.

**Comment by matthewcheok** [comment]
Do you have a sample project I can take a look at?

**Comment by yongeli** [comment]
Thanks for the really quick reply, I've made a sample project hopefully to demonstrate what I mean

https://github.com/Sxcerino/sample

Thank you

**Comment by matthewcheok** [comment]
Hey this is not really a issue with `MCPanelViewController`.
`UIPanGestureRecognizer` is a continuous gesture recogniser and calls its selector many times.

This should fix this issue:

```
- (void)panGestureRecognized:(UIPanGestureRecognizer *)pan
{
    // Dismiss keyboard (optional)
    //
    switch (pan.state) {
        case UIGestureRecognizerStateBegan:
            [self.view endEditing:YES];
            [self.tabBarController presentPanelViewController:tintedPanelViewController withDirection:MCPanelAnimationDirectionLeft];
            break;

        case UIGestureRecognizerStateChanged:
            break;

        case UIGestureRecognizerStateEnded:
        case UIGestureRecognizerStateCancelled:
           break;

        default:
            break;
    }
}
```

**Comment by yongeli** [comment]
My mistake! Thanks a lot for your help.

Although One last question however - would it be possible to still animate the dynamic effect from edge pan dragging into the general gesture recognizer? or if there is anyway really quickly to modify the edge pan to gesture pan?

Thanks again, much appreciated.
