### ISSUE TITLE
Can I disappear the statusBar?

### ISSUE THREAD

**Issue by say8425** [matthewcheok/MCPanelViewController#13]
Hello. I use this code, and it great works.
But i want to disappear the statusBar of Panel

So I code `[[UIApplication sharedApplication]setStatusBarHidden:YES;` but it doesn't work.
How can I disappear the statusBar?
![2014-08-14 8 49 54](https://cloud.githubusercontent.com/assets/3258867/3919519/b0382120-23a9-11e4-9b14-4f09b8abf545.png)

**Comment by matthewcheok** [comment]
See http://stackoverflow.com/questions/18059703/cannot-hide-status-bar-in-ios7
