### ISSUE TITLE
Make parts of screen that aren't covered by slideout interactive and tappable

### ISSUE THREAD

**Issue by jlr** [matthewcheok/MCPanelViewController#3]
Hi,

Thanks for the excellent slideout widget. It's a really huge boost to the app I'm building and I'm very grateful that you've released it. 

I have been studying your code for over a week now (I think I found it the day it was released - Oct 5?). I can't seem to figure out something that ought to be trivial. I want slideouts to only obscure the portion of the screen which they actually cover, so that you can still tap any other part of the screen and interact with it normally.

I've disabled the backgroundButton property and the shadow that appears over the remainder of the screen when you slide out, and also looked in detail at various CGRect and CGBounds properties to see if I'm missing any views that cover the whole screen. But I'm just not seeing what's preventing tap gestures to go through when a MCPanelView is slid out.

Could you give me some form of pointer towards solving this? It would be extremely helpful to me. 

Thanks again for releasing such high quality and beautiful code. This slideout widget makes a big difference for me.

**Comment by matthewcheok** [comment]
That's because the MCPanelViewController's view itself is consuming the touches. This view is transparent and completely covers the parent view controller (presenting view controller) and your presented view controller's view is then added as a subview to it.

One possible solution is replace this view with a subclass that overwrites the `- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event` method to allow touches not inside the view of the presented view controller (rootViewController property) to pass through.

**Comment by jlr** [comment]
Thanks very much. That did it.

**Comment by lemak5** [comment]
Hi, 
I tried to implement this solution in your example but I did not succeed. 
Can you help me? 
Thank you in advance

**Comment by matthewcheok** [comment]
Can you elaborate how you have implemented the solution?

**Comment by lemak5** [comment]
Hi Matthewcheok,

Thanks for your answer :)
I am a beginner in iOS programming. I certainly made ​​mistakes. 
Here is my implementation: 
I created a subclass of UIView class: 
@interface MCCustomView : UIView
with: 
- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event {
  return YES;
  }
  (I also tried to overwrite the function: - (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event)

In the initWithRootViewController method of MCPanelViewController, I added: 
object_setClass(self.view, [MCCustomView class]);

I also tried to change the frame properties and bounds of the view without success.

PS : sorry for my english!

**Comment by lemak5** [comment]
Small addition: 

I deleted also all references to:  shadowView, imageView & backgroundButton

**Comment by matthewcheok** [comment]
You can overwrite `- (void)loadView` and specify `self.view = [[MCCustomView alloc] init]` to specify the class to be used for the view controller.

**Comment by lemak5** [comment]
The result is the same as my implementation. 
The pointInside's method is called (twice) but the buttons called "Left" and "Push view controller" remain inactive :(
Should i resize the frame of the MCPanelViewController's view ?

**Comment by matthewcheok** [comment]
Here's an implementation for `MCCustomView`:

```
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    UIView *view = [super hitTest:point withEvent:event];
    return view == self ? nil : view;
}
```

This essentially means that areas within the view that do not contain subviews will be regarded as not 'inside' of the view, and will pass touches to whatever is behind (like your buttons).

**Comment by lemak5** [comment]
Thank you ! It Works! 
One more thing if it is possible : 
What changes should I make to MCPanelViewController class for :
- If the user drags the right panel to the left beyond the maximum width, the panel fills the screen 
- If this panel fills the screen and the user drags to the right short of the maximum width, the width of the panel is the maximum width.

Thank you for your job and your help !
