### ISSUE TITLE
Can't dismiss panel

### ISSUE THREAD

**Issue by shmidt** [matthewcheok/MCPanelViewController#5]
I'm trying to dismiss panel from panel.
I made an exit segue in root view controller and tried `[_lightPanelViewController dismiss];`.
This gave me some strange effect — panel was closed but navigation bar get lost.
(I use iOS7).

What is the right way to dismiss a panel?

**Comment by matthewcheok** [comment]
Typically I would suggest dismissing from the presenting view controller or the `parentViewControlller` property on `MCPanelViewController`. You could do this via delegation or as long as you have a reference to the same `MCPanelViewController` you presented.

If you still need help, attach your project and I'll take a look.

**Comment by aspergatus** [comment]
Hi, can you show me how to dismiss? I could not figure out.

**Comment by matthewcheok** [comment]
If you're using the latest release, you can call the following from your presented view controller (after importing headers)

```
[self.panelViewController dismiss];
```

**Comment by aspergatus** [comment]
Hey thanks for quick response!
