### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by jcampbell05** [matthewcheok/MCPanelViewController#7]
How will I update the width of the side panels upon rotation ? Also is there a way to have them thinner on the iPhone ?

**Comment by matthewcheok** [comment]
You can set the width using `preferredContentSize` property. The height is ignored.
Unfortunately there’s no way to set widths for different orientations at the moment.

If you’d like to add this, you can try adjusting the internal `maxWidth` property inside the UIViewController rotation methods and then call `- (void)layoutSubviewsToWidth:(CGFloat)width` inside an animation block to update the UI.
